#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PIS_G18C

#include "Basic.hpp"

#include "ABP_PIS_G18C_classes.hpp"
#include "ABP_PIS_G18C_parameters.hpp"


namespace SDK
{

// Function ABP_PIS_G18C.ABP_PIS_G18C_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_PIS_G18C_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PIS_G18C_C", "AnimGraph");

	Params::ABP_PIS_G18C_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_PIS_G18C.ABP_PIS_G18C_C.AnimNotify_DropSpeedReloadMagazine
// (BlueprintCallable, BlueprintEvent)

void UABP_PIS_G18C_C::AnimNotify_DropSpeedReloadMagazine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PIS_G18C_C", "AnimNotify_DropSpeedReloadMagazine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PIS_G18C.ABP_PIS_G18C_C.AnimNotify_ShowMag
// (BlueprintCallable, BlueprintEvent)

void UABP_PIS_G18C_C::AnimNotify_ShowMag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PIS_G18C_C", "AnimNotify_ShowMag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PIS_G18C.ABP_PIS_G18C_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PIS_G18C_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PIS_G18C_C", "BlueprintUpdateAnimation");

	Params::ABP_PIS_G18C_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_PIS_G18C.ABP_PIS_G18C_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PIS_G18C_AnimGraphNode_BlendListByBool_F2D45D384AB25E2260FF9B861D4647D6
// (BlueprintEvent)

void UABP_PIS_G18C_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PIS_G18C_AnimGraphNode_BlendListByBool_F2D45D384AB25E2260FF9B861D4647D6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PIS_G18C_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PIS_G18C_AnimGraphNode_BlendListByBool_F2D45D384AB25E2260FF9B861D4647D6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PIS_G18C.ABP_PIS_G18C_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PIS_G18C_AnimGraphNode_ModifyBone_39241F354F7963806613B09F410EE323
// (BlueprintEvent)

void UABP_PIS_G18C_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PIS_G18C_AnimGraphNode_ModifyBone_39241F354F7963806613B09F410EE323()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PIS_G18C_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PIS_G18C_AnimGraphNode_ModifyBone_39241F354F7963806613B09F410EE323");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PIS_G18C.ABP_PIS_G18C_C.ExecuteUbergraph_ABP_PIS_G18C
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PIS_G18C_C::ExecuteUbergraph_ABP_PIS_G18C(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PIS_G18C_C", "ExecuteUbergraph_ABP_PIS_G18C");

	Params::ABP_PIS_G18C_C_ExecuteUbergraph_ABP_PIS_G18C Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

