#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_RIF_RTWC

#include "Basic.hpp"

#include "ABP_RIF_RTWC_classes.hpp"
#include "ABP_RIF_RTWC_parameters.hpp"


namespace SDK
{

// Function ABP_RIF_RTWC.ABP_RIF_RTWC_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_RIF_RTWC_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_RIF_RTWC_C", "AnimGraph");

	Params::ABP_RIF_RTWC_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_RIF_RTWC.ABP_RIF_RTWC_C.AnimNotify_DropSpeedReloadMagazine
// (BlueprintCallable, BlueprintEvent)

void UABP_RIF_RTWC_C::AnimNotify_DropSpeedReloadMagazine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_RIF_RTWC_C", "AnimNotify_DropSpeedReloadMagazine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_RIF_RTWC.ABP_RIF_RTWC_C.AnimNotify_ShowMag
// (BlueprintCallable, BlueprintEvent)

void UABP_RIF_RTWC_C::AnimNotify_ShowMag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_RIF_RTWC_C", "AnimNotify_ShowMag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_RIF_RTWC.ABP_RIF_RTWC_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_RIF_RTWC_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_RIF_RTWC_C", "BlueprintUpdateAnimation");

	Params::ABP_RIF_RTWC_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_RIF_RTWC.ABP_RIF_RTWC_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_RIF_RTWC_AnimGraphNode_BlendListByBool_130671B8438139EC26037DAE7D7B1EAC
// (BlueprintEvent)

void UABP_RIF_RTWC_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_RIF_RTWC_AnimGraphNode_BlendListByBool_130671B8438139EC26037DAE7D7B1EAC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_RIF_RTWC_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_RIF_RTWC_AnimGraphNode_BlendListByBool_130671B8438139EC26037DAE7D7B1EAC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_RIF_RTWC.ABP_RIF_RTWC_C.ExecuteUbergraph_ABP_RIF_RTWC
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_RIF_RTWC_C::ExecuteUbergraph_ABP_RIF_RTWC(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_RIF_RTWC_C", "ExecuteUbergraph_ABP_RIF_RTWC");

	Params::ABP_RIF_RTWC_C_ExecuteUbergraph_ABP_RIF_RTWC Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

