#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_NearbyHostage

#include "Basic.hpp"

#include "AG_NearbyHostage_classes.hpp"
#include "AG_NearbyHostage_parameters.hpp"


namespace SDK
{

// Function AG_NearbyHostage.AG_NearbyHostage_C.FindCiviliansInRange
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class ACyberneticCharacter*             Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<class ACivilianCharacter*>*      Return_Value                                           (Parm, OutParm)

void UAG_NearbyHostage_C::FindCiviliansInRange(class ACyberneticCharacter* Start, TArray<class ACivilianCharacter*>* Return_Value) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AG_NearbyHostage_C", "FindCiviliansInRange");

	Params::AG_NearbyHostage_C_FindCiviliansInRange Parms{};

	Parms.Start = Start;

	UObject::ProcessEvent(Func, &Parms);

	if (Return_Value != nullptr)
		*Return_Value = std::move(Parms.Return_Value);
}


// Function AG_NearbyHostage.AG_NearbyHostage_C.CanOpen
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FAIActionDecisionContext&  Context                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UAG_NearbyHostage_C::CanOpen(const struct FAIActionDecisionContext& Context) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AG_NearbyHostage_C", "CanOpen");

	Params::AG_NearbyHostage_C_CanOpen Parms{};

	Parms.Context = std::move(Context);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

