#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_NearbyHostage

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AG_NearbyHostage.AG_NearbyHostage_C
// 0x0008 (0x0030 - 0x0028)
class UAG_NearbyHostage_C final : public UAIActionGate
{
public:
	double                                        SearchRange;                                       // 0x0028(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void FindCiviliansInRange(class ACyberneticCharacter* Start, TArray<class ACivilianCharacter*>* Return_Value) const;
	bool CanOpen(const struct FAIActionDecisionContext& Context) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AG_NearbyHostage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AG_NearbyHostage_C")
	}
	static class UAG_NearbyHostage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAG_NearbyHostage_C>();
	}
};
DUMPER7_ASSERTS_UAG_NearbyHostage_C;

}

