#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BasePlayer_Ending

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BasePlayer_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BasePlayer_Ending.BasePlayer_Ending_C
// 0x0000 (0x3190 - 0x3190)
class ABasePlayer_Ending_C final : public ABasePlayer_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BasePlayer_Ending_C;                // 0x3188(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BasePlayer_Ending(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BasePlayer_Ending_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BasePlayer_Ending_C")
	}
	static class ABasePlayer_Ending_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABasePlayer_Ending_C>();
	}
};
DUMPER7_ASSERTS_ABasePlayer_Ending_C;

}

