#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BasePlayer_Ending

#include "Basic.hpp"


namespace SDK::Params
{

// Function BasePlayer_Ending.BasePlayer_Ending_C.ExecuteUbergraph_BasePlayer_Ending
// 0x0004 (0x0004 - 0x0000)
struct BasePlayer_Ending_C_ExecuteUbergraph_BasePlayer_Ending final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BasePlayer_Ending_C_ExecuteUbergraph_BasePlayer_Ending;

}

