#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Compensator_ASR

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Compensator_ASR.BP_Compensator_ASR_C
// 0x0000 (0x10D0 - 0x10D0)
class UBP_Compensator_ASR_C final : public UWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Compensator_ASR_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Compensator_ASR_C")
	}
	static class UBP_Compensator_ASR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Compensator_ASR_C>();
	}
};
DUMPER7_ASSERTS_UBP_Compensator_ASR_C;

}

