#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Detonator_Activation_Proxy

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Detonator_Activation_Proxy.BP_Detonator_Activation_Proxy_C
// 0x0000 (0x02D8 - 0x02D8)
class ABP_Detonator_Activation_Proxy_C final : public ATowerDetonatorActivationProxy
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Detonator_Activation_Proxy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Detonator_Activation_Proxy_C")
	}
	static class ABP_Detonator_Activation_Proxy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Detonator_Activation_Proxy_C>();
	}
};
DUMPER7_ASSERTS_ABP_Detonator_Activation_Proxy_C;

}

