#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionBuilder_MissionSelectionListItemEntry

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_MissionBuilder_MissionSelectionListItemEntry.BP_MissionBuilder_MissionSelectionListItemEntry_C.Hover
// 0x0001 (0x0001 - 0x0000)
struct BP_MissionBuilder_MissionSelectionListItemEntry_C_Hover final
{
public:
	bool                                          IsHovered;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_MissionBuilder_MissionSelectionListItemEntry_C_Hover;

// Function BP_MissionBuilder_MissionSelectionListItemEntry.BP_MissionBuilder_MissionSelectionListItemEntry_C.Select
// 0x0001 (0x0001 - 0x0000)
struct BP_MissionBuilder_MissionSelectionListItemEntry_C_Select final
{
public:
	bool                                          IsSelected;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_MissionBuilder_MissionSelectionListItemEntry_C_Select;

// Function BP_MissionBuilder_MissionSelectionListItemEntry.BP_MissionBuilder_MissionSelectionListItemEntry_C.SetFavourite
// 0x0001 (0x0001 - 0x0000)
struct BP_MissionBuilder_MissionSelectionListItemEntry_C_SetFavourite final
{
public:
	bool                                          bFavourite_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_MissionBuilder_MissionSelectionListItemEntry_C_SetFavourite;

// Function BP_MissionBuilder_MissionSelectionListItemEntry.BP_MissionBuilder_MissionSelectionListItemEntry_C.SetPresetName
// 0x0018 (0x0018 - 0x0000)
struct BP_MissionBuilder_MissionSelectionListItemEntry_C_SetPresetName final
{
public:
	class FText                                   PresetName_0;                                      // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_BP_MissionBuilder_MissionSelectionListItemEntry_C_SetPresetName;

}

