#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionBuilder_MapSelectionListItemEntry

#include "Basic.hpp"

#include "ReadyOrNot_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MissionBuilder_MapSelectionListItemEntry.BP_MissionBuilder_MapSelectionListItemEntry_C
// 0x0910 (0x0938 - 0x0028)
class UBP_MissionBuilder_MapSelectionListItemEntry_C final : public UObject
{
public:
	class FString                                 LevelID;                                           // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsLocked;                                          // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLevelDataLookupTable                  LevelData;                                         // 0x0040(0x08D0)(Edit, BlueprintVisible, ExposeOnSpawn)
	TMulticastInlineDelegate<void(bool IsSelected)> SelectEvent;                                     // 0x0910(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool IsHovered)> HoverEvent;                                       // 0x0920(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          ShouldBeSelected;                                  // 0x0930(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bNotOwned;                                         // 0x0931(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void Hover(bool IsHovered);
	void Select(bool Selected);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MissionBuilder_MapSelectionListItemEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MissionBuilder_MapSelectionListItemEntry_C")
	}
	static class UBP_MissionBuilder_MapSelectionListItemEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MissionBuilder_MapSelectionListItemEntry_C>();
	}
};
DUMPER7_ASSERTS_UBP_MissionBuilder_MapSelectionListItemEntry_C;

}

