#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_M9_Brake

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_M9_Brake.BP_M9_Brake_C
// 0x0000 (0x10D0 - 0x10D0)
class UBP_M9_Brake_C final : public UWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_M9_Brake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_M9_Brake_C")
	}
	static class UBP_M9_Brake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_M9_Brake_C>();
	}
};
DUMPER7_ASSERTS_UBP_M9_Brake_C;

}

