#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionBuilder_MissionSelectionListItemEntry

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MissionBuilder_MissionSelectionListItemEntry.BP_MissionBuilder_MissionSelectionListItemEntry_C
// 0x00A8 (0x00D0 - 0x0028)
class UBP_MissionBuilder_MissionSelectionListItemEntry_C final : public UObject
{
public:
	int32                                         Index_0;                                           // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 MissionMapName;                                    // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	int64                                         Date;                                              // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FGameplayTag                           Difficulty;                                        // 0x0048(0x0008)(Edit, BlueprintVisible, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UTexture2D*                             MapImage;                                          // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 MissionDescription;                                // 0x0058(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool IsSelected)> SelectEvent;                                     // 0x0068(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool IsHovered)> HoverEvent;                                       // 0x0078(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bFavourite;                                        // 0x0088(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(int32 PresetIndex, bool bFavourite)> OnFavouritePressed;           // 0x0090(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bFavouriteEnabled;                                 // 0x00A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bIsEmptySlot;                                      // 0x00A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bShouldBeSelected;                                 // 0x00A2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_A3[0x5];                                       // 0x00A3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(int32 PresetIndex, class FText PresetName)> OnPresetNameCommitted; // 0x00A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FText                                   PresetName;                                        // 0x00B8(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void Hover(bool IsHovered);
	void Select(bool IsSelected);
	void SetFavourite(bool bFavourite_0);
	void SetPresetName(const class FText& PresetName_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MissionBuilder_MissionSelectionListItemEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MissionBuilder_MissionSelectionListItemEntry_C")
	}
	static class UBP_MissionBuilder_MissionSelectionListItemEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MissionBuilder_MissionSelectionListItemEntry_C>();
	}
};
DUMPER7_ASSERTS_UBP_MissionBuilder_MissionSelectionListItemEntry_C;

}

