#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Primary_Mossberg590Mv2_FDE

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Primary_Mossberg590Mv2_FDE.BP_Primary_Mossberg590Mv2_FDE_C
// 0x0010 (0x19B0 - 0x19A0)
class ABP_Primary_Mossberg590Mv2_FDE_C final : public ABaseMagazineWeapon
{
public:
	uint8                                         Pad_1998[0x8];                                     // 0x1998(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x19A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Primary_Mossberg590Mv2_FDE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Primary_Mossberg590Mv2_FDE_C")
	}
	static class ABP_Primary_Mossberg590Mv2_FDE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Primary_Mossberg590Mv2_FDE_C>();
	}
};
DUMPER7_ASSERTS_ABP_Primary_Mossberg590Mv2_FDE_C;

}

