#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Primary_Mossberg590Mv2_FDE

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Primary_Mossberg590Mv2_FDE.BP_Primary_Mossberg590Mv2_FDE_C.ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE
// 0x0004 (0x0004 - 0x0000)
struct BP_Primary_Mossberg590Mv2_FDE_C_ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Primary_Mossberg590Mv2_FDE_C_ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE;

}

