#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Primary_Mossberg590Mv2_FDE

#include "Basic.hpp"

#include "BP_Primary_Mossberg590Mv2_FDE_classes.hpp"
#include "BP_Primary_Mossberg590Mv2_FDE_parameters.hpp"


namespace SDK
{

// Function BP_Primary_Mossberg590Mv2_FDE.BP_Primary_Mossberg590Mv2_FDE_C.ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Primary_Mossberg590Mv2_FDE_C::ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Primary_Mossberg590Mv2_FDE_C", "ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE");

	Params::BP_Primary_Mossberg590Mv2_FDE_C_ExecuteUbergraph_BP_Primary_Mossberg590Mv2_FDE Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Primary_Mossberg590Mv2_FDE.BP_Primary_Mossberg590Mv2_FDE_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Primary_Mossberg590Mv2_FDE_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Primary_Mossberg590Mv2_FDE_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

