#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SuspectToxicBackpack

#include "Basic.hpp"

#include "BP_SuspectToxicBackpack_classes.hpp"
#include "BP_SuspectToxicBackpack_parameters.hpp"


namespace SDK
{

// Function BP_SuspectToxicBackpack.BP_SuspectToxicBackpack_C.ExecuteUbergraph_BP_SuspectToxicBackpack
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SuspectToxicBackpack_C::ExecuteUbergraph_BP_SuspectToxicBackpack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SuspectToxicBackpack_C", "ExecuteUbergraph_BP_SuspectToxicBackpack");

	Params::BP_SuspectToxicBackpack_C_ExecuteUbergraph_BP_SuspectToxicBackpack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SuspectToxicBackpack.BP_SuspectToxicBackpack_C.ReceiveAnyDamage
// (BlueprintAuthorityOnly, Event, Public, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UDamageType*                DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_SuspectToxicBackpack_C::ReceiveAnyDamage(float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SuspectToxicBackpack_C", "ReceiveAnyDamage");

	Params::BP_SuspectToxicBackpack_C_ReceiveAnyDamage Parms{};

	Parms.Damage = Damage;
	Parms.DamageType = DamageType;
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SuspectToxicBackpack.BP_SuspectToxicBackpack_C.RPC_MeshSwap
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_SuspectToxicBackpack_C::RPC_MeshSwap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SuspectToxicBackpack_C", "RPC_MeshSwap");

	UObject::ProcessEvent(Func, nullptr);
}

}

