#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Default10ptTextStyleUpperCaseAlignRight

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Default10ptTextStyleUpperCaseAlignRight.Default10ptTextStyleUpperCaseAlignRight_C
// 0x0000 (0x01B0 - 0x01B0)
class UDefault10ptTextStyleUpperCaseAlignRight_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Default10ptTextStyleUpperCaseAlignRight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Default10ptTextStyleUpperCaseAlignRight_C")
	}
	static class UDefault10ptTextStyleUpperCaseAlignRight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefault10ptTextStyleUpperCaseAlignRight_C>();
	}
};
DUMPER7_ASSERTS_UDefault10ptTextStyleUpperCaseAlignRight_C;

}

