#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Default_18pt_TextStyleAlignRight

#include "Basic.hpp"

#include "DefaultNormalTextStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Default_18pt_TextStyleAlignRight.Default_18pt_TextStyleAlignRight_C
// 0x0000 (0x01B0 - 0x01B0)
class UDefault_18pt_TextStyleAlignRight_C final : public UDefaultNormalTextStyle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Default_18pt_TextStyleAlignRight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Default_18pt_TextStyleAlignRight_C")
	}
	static class UDefault_18pt_TextStyleAlignRight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefault_18pt_TextStyleAlignRight_C>();
	}
};
DUMPER7_ASSERTS_UDefault_18pt_TextStyleAlignRight_C;

}

