#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pistol_Compensator_Double

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Pistol_Compensator_Double.Pistol_Compensator_Double_C
// 0x0000 (0x10D0 - 0x10D0)
class UPistol_Compensator_Double_C final : public UWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Pistol_Compensator_Double_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Pistol_Compensator_Double_C")
	}
	static class UPistol_Compensator_Double_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPistol_Compensator_Double_C>();
	}
};
DUMPER7_ASSERTS_UPistol_Compensator_Double_C;

}

