#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scope_MP5_SRO

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Scope_MP5_SRO.Scope_MP5_SRO_C
// 0x0000 (0x1940 - 0x1940)
class UScope_MP5_SRO_C final : public UScopedWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Scope_MP5_SRO_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Scope_MP5_SRO_C")
	}
	static class UScope_MP5_SRO_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScope_MP5_SRO_C>();
	}
};
DUMPER7_ASSERTS_UScope_MP5_SRO_C;

}

