#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scope_SRS_Raised

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Scope_SRS_Raised.Scope_SRS_Raised_C
// 0x0000 (0x1840 - 0x1840)
class UScope_SRS_Raised_C final : public UScopedWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Scope_SRS_Raised_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Scope_SRS_Raised_C")
	}
	static class UScope_SRS_Raised_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScope_SRS_Raised_C>();
	}
};
DUMPER7_ASSERTS_UScope_SRS_Raised_C;

}

