#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Secondary_Taser_V2

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Secondary_Taser_V2.Secondary_Taser_V2_C
// 0x0030 (0x1D70 - 0x1D40)
class ASecondary_Taser_V2_C final : public ATaser
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1D40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        OverallTaserWireLength;                            // 0x1D48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                LastLocation;                                      // 0x1D50(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DestroyPouches_1();
	void ExecuteUbergraph_Secondary_Taser_V2(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void SpawnPouches_1();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Secondary_Taser_V2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Secondary_Taser_V2_C")
	}
	static class ASecondary_Taser_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASecondary_Taser_V2_C>();
	}
};
DUMPER7_ASSERTS_ASecondary_Taser_V2_C;

}

