#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_CMBCheckSlider_CheckArea

#include "Basic.hpp"

#include "W_CMBCheckSlider_CheckArea_classes.hpp"
#include "W_CMBCheckSlider_CheckArea_parameters.hpp"


namespace SDK
{

// Function W_CMBCheckSlider_CheckArea.W_CMBCheckSlider_CheckArea_C.BndEvt__W_CMBCheckSlider_CheckArea_CheckAreaButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_CMBCheckSlider_CheckArea_C::BndEvt__W_CMBCheckSlider_CheckArea_CheckAreaButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CMBCheckSlider_CheckArea_C", "BndEvt__W_CMBCheckSlider_CheckArea_CheckAreaButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_CMBCheckSlider_CheckArea.W_CMBCheckSlider_CheckArea_C.ExecuteUbergraph_W_CMBCheckSlider_CheckArea
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_CMBCheckSlider_CheckArea_C::ExecuteUbergraph_W_CMBCheckSlider_CheckArea(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CMBCheckSlider_CheckArea_C", "ExecuteUbergraph_W_CMBCheckSlider_CheckArea");

	Params::W_CMBCheckSlider_CheckArea_C_ExecuteUbergraph_W_CMBCheckSlider_CheckArea Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_CMBCheckSlider_CheckArea.W_CMBCheckSlider_CheckArea_C.FillProgressBar
// (Public, BlueprintCallable, BlueprintEvent)

void UW_CMBCheckSlider_CheckArea_C::FillProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CMBCheckSlider_CheckArea_C", "FillProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_CMBCheckSlider_CheckArea.W_CMBCheckSlider_CheckArea_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_CMBCheckSlider_CheckArea_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CMBCheckSlider_CheckArea_C", "PreConstruct");

	Params::W_CMBCheckSlider_CheckArea_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_CMBCheckSlider_CheckArea.W_CMBCheckSlider_CheckArea_C.ResetSelection
// (Public, BlueprintCallable, BlueprintEvent)

void UW_CMBCheckSlider_CheckArea_C::ResetSelection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CMBCheckSlider_CheckArea_C", "ResetSelection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_CMBCheckSlider_CheckArea.W_CMBCheckSlider_CheckArea_C.SetSelected
// (Public, BlueprintCallable, BlueprintEvent)

void UW_CMBCheckSlider_CheckArea_C::SetSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CMBCheckSlider_CheckArea_C", "SetSelected");

	UObject::ProcessEvent(Func, nullptr);
}

}

