#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_EmptyTextSection

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_EmptyTextSection.W_EmptyTextSection_C
// 0x0008 (0x02D0 - 0x02C8)
class UW_EmptyTextSection_C final : public UUserWidget
{
public:
	class UCommonTextBlock*                       EmptyText;                                         // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_EmptyTextSection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_EmptyTextSection_C")
	}
	static class UW_EmptyTextSection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_EmptyTextSection_C>();
	}
};
DUMPER7_ASSERTS_UW_EmptyTextSection_C;

}

