#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilderPageBtn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C
// 0x0040 (0x0308 - 0x02C8)
class UW_MissionBuilderPageBtn_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UW_OnOffButton_C*                       W_PageButton;                                      // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool bEnabled, const struct FGameplayTag& EntryTag)> OnStateChanged; // 0x02D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FGameplayTag                           EntryTag;                                          // 0x02E8(0x0008)(Edit, BlueprintVisible, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 PageIndex)> OnPageButtonClicked;                             // 0x02F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         PageIndex;                                         // 0x0300(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature(bool bNewCheckState);
	void BndEvt__W_MissionBuilderCategoryBtn_W_CategoryButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_W_MissionBuilderPageBtn(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetButtonSelected(bool bSelected);
	void SetButtonText(const class FText& CategoryText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilderPageBtn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilderPageBtn_C")
	}
	static class UW_MissionBuilderPageBtn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilderPageBtn_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilderPageBtn_C;

}

