#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_DropDown

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "w_Dropdown_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_DropDown.W_MissionBuilder_DropDown_C
// 0x0040 (0x0518 - 0x04D8)
class UW_MissionBuilder_DropDown_C final : public Uw_Dropdown_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_MissionBuilder_DropDown_C;        // 0x04D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   PropertyName;                                      // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class FName PropertyName, const class FString& OptionID)> OnMBDropdownOptionSelected; // 0x04E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bIsUndefined;                                      // 0x04F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4F9[0x7];                                      // 0x04F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class Uw_DropdownMenu_C*                      DropdownMenuRef;                                   // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FString                                 CurrentHoveredOptions;                             // 0x0508(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_MissionBuilder_DropDown(int32 EntryPoint);
	class UWidget* OnDropdownMenuDown(EUINavigation Navigation_0);
	void OnDropdownOptionSelected(const class FString& OptionID);
	struct FEventReply OnMouseWheel(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void SetUndefined(bool IsUndefined);
	void Construct();
	class UUserWidget* On_DropdownMenuAnchor_GetUserMenuContent_0();
	void OnDropdown_Menu_Desired_Focus_Set(class UW_Button_C* DesiredFocus);
	void OptionHovered(const class FString& OptionID);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_DropDown_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_DropDown_C")
	}
	static class UW_MissionBuilder_DropDown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_DropDown_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_DropDown_C;

}

