#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_CheckboxArray

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_CheckboxArray.W_MissionBuilder_CheckboxArray_C
// 0x0058 (0x0320 - 0x02C8)
class UW_MissionBuilder_CheckboxArray_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           VerticalBox_48;                                    // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FName                                   PropertyID;                                        // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class FName PropertyID, TArray<int32>& CheckedOptions)> OnCheckboxArrayOptionsChanged; // 0x02E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class FText>                           CheckboxOptions;                                   // 0x02F0(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	TArray<int32>                                 CheckedOptions;                                    // 0x0300(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          bDoCallback;                                       // 0x0310(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bLastElementExcluded;                              // 0x0311(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_312[0x2];                                      // 0x0312(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LastCheckedIndex;                                  // 0x0314(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UScrollBox*                             OwningScrollBox;                                   // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_W_MissionBuilder_CheckboxArray(int32 EntryPoint);
	void GetFirstElementWidget(class UUserWidget** FirstElementWidget);
	void GetValues(TArray<int32>* CheckedOptions_0);
	void OnCheckboxElementHovered(class UUserWidget* Button);
	void OnCheckboxOptionChanged(int32 Index_0, bool IsChecked);
	void SetLastElementVisibility(bool bShouldBeVisible);
	void SetUndefined(bool IsUndefined);
	void SetValues(TArray<int32>& SelectedOptions, bool bWithCallback);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_CheckboxArray_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_CheckboxArray_C")
	}
	static class UW_MissionBuilder_CheckboxArray_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_CheckboxArray_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_CheckboxArray_C;

}

