#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilderProperties

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "ReadyOrNot_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilderProperties.W_MissionBuilderProperties_C
// 0x0068 (0x0588 - 0x0520)
class UW_MissionBuilderProperties_C final : public UMissionBuilderPropertiesWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0520(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UW_MissionBuilderPropertyContainer_C*   GrenadeStun;                                       // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilderPropertyContainer_C*   StunHealth;                                        // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilderPropertyContainer_C*   TestCheckboxArrayProperty;                         // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilderPropertyContainer_C*   TestCheckboxProperty;                              // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilderPropertyContainer_C*   TestDifficultyProperty;                            // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilderPropertyContainer_C*   TestDropdownProperty;                              // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_StandardSlider_C*                    TestSlider;                                        // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_CheckSlider_C*        W_CMB_CheckSlider;                                 // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_CheckboxArray_C*      W_MissionBuilder_CheckboxArray;                    // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_MissionSelectionDifficultySelection_C* W_MissionBuilder_DifficultyButtons; // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_DropDown_C*           W_MissionBuilder_DropDown;                         // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_OnOffButton_C*                       W_OnOffButton;                                     // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_MissionBuilderProperties(int32 EntryPoint);
	const TArray<int32> GetCheckboxArrayPropertyValueBP(class UUserWidget* DropdownWidget);
	const bool GetCheckboxPropertyValueBP(class UUserWidget* CheckboxWidget);
	const int32 GetDifficultyPropertyValueBP(class UUserWidget* DifficultyWidget);
	const class FString GetDropdownPropertyValueBP(class UUserWidget* DropdownWidget);
	void GetFirstProperty(class UWidget** FirstProperty);
	const float GetSliderFloatPropertyValueBP(class UUserWidget* SliderFloatWidget);
	const int32 GetSliderIntegerPropertyValueBP(class UUserWidget* SliderIntegerWidget);
	const int32 GetStepSliderPropertyValueBP(class UUserWidget* StepSliderWidget);
	void OnCheckboxArrayOptionsChanged(class FName PropertyID, TArray<int32>& CheckedOptions);
	void OnCheckboxArrayPropertyAdded(class UUserWidget* CheckboxArrayWidget, const class FName& PropertyName, const class FText& PropertyLocName, const class FText& PropertyTooltip, const TSoftObjectPtr<class UTexture2D>& TooltipTexture, const struct FMissionBuilderCheckboxArrayData& UISettings, const TArray<int32>& DefaultValues, const bool bIsModified, const bool bUseUndefined);
	void OnCheckboxArrayPropertyHover(const class FText& ToolTip, TSoftObjectPtr<class UTexture2D> TooltipTexture, class UW_MissionBuilderPropertyContainer_C* Property);
	void OnCheckboxArrayPropertyUpdated(class UUserWidget* CheckboxArrayWidget, const TArray<int32>& UpdatedValue, bool bShouldBeActive);
	void OnCheckboxArrayResetToDefault(class UUserWidget* PropertyContentWidget, bool bUseUndefined);
	void OnCheckboxConnection(class UUserWidget* ConnectedWidget, EMissionBuilderConnectionUsage ConnectionUsage, const bool UpdatedValue);
	void OnCheckboxPropertyAdded(class UUserWidget* CheckboxWidget, const class FName& PropertyName, const class FText& PropertyLocName, const class FText& PropertyTooltip, const TSoftObjectPtr<class UTexture2D>& TooltipTexture, bool DefaultValue, const bool bIsModified, const bool bUseUndefined);
	void OnCheckboxPropertyHover(const class FText& ToolTip, TSoftObjectPtr<class UTexture2D> TooltipTexture, class UW_MissionBuilderPropertyContainer_C* Property);
	void OnCheckboxPropertyResetToDefault(class UUserWidget* PropertyContentWidget, bool bUseUndefined);
	void OnCheckboxPropertyUpdated(class UUserWidget* CheckboxWidget, const bool UpdatedValue, bool bShouldBeActive);
	void OnCheckBoxStateChanged(class FName PropertyName, bool NewBoolValue);
	void OnDifficultyPropertyAdded(class UUserWidget* DifficultyWidget, const class FName& PropertyName, const class FText& PropertyLocName, const class FText& PropertyTooltip, const TSoftObjectPtr<class UTexture2D>& TooltipTexture, EMissionBuilderDifficultyPropertyValues DefaultValue, const bool bIsModified, const bool bUseUndefined);
	void OnDifficultyPropertyHover(const class FText& ToolTip, TSoftObjectPtr<class UTexture2D> TooltipTexture, class UW_MissionBuilderPropertyContainer_C* Property);
	void OnDifficultyPropertyUpdated(class UUserWidget* DifficultyWidget, const EMissionBuilderDifficultyPropertyValues UpdatedValue, bool bShouldBeActive);
	void OnDifficultyResetToDefault(class UUserWidget* PropertyContentWidget, bool bUseUndefined);
	void OnDifficultyValueChanged(class FName PropertyName, EMissionBuilderDifficultyPropertyValues NewDifficultyValue);
	void OnDropdownOptionSelected(class FName PropertyName, const class FString& OptionID);
	void OnDropdownPropertyAdded(class UUserWidget* DropdownWidget, const class FName& PropertyName, const class FText& PropertyLocName, const class FText& PropertyTooltip, const TSoftObjectPtr<class UTexture2D>& TooltipTexture, const struct FMissionBuilderDropdownData& UISettings, const class FString& DefaultValue, const bool bIsModified, const bool bUseUndefined);
	void OnDropdownPropertyHover(const class FText& ToolTip, TSoftObjectPtr<class UTexture2D> TooltipTexture, class UW_MissionBuilderPropertyContainer_C* Property);
	void OnDropdownPropertyUpdated(class UUserWidget* DropdownWidget, const class FString& UpdatedValue, bool bShouldBeActive);
	void OnDropdownResetToDefault(class UUserWidget* PropertyContentWidget, bool bUseUndefined);
	void OnSliderFloatPropertyUpdated(class UUserWidget* SliderWidget, const float& UpdatedValue, bool bShouldBeActive);
	void OnSliderFloatValueChanged(class FName PropertyName, double NewFloatValue, double NewSliderValue);
	void OnSliderIntegerConnection(class UUserWidget* ConnectedWidget, EMissionBuilderConnectionUsage ConnectionUsage, const int32& UpdatedValue);
	void OnSliderIntegerPropertyUpdated(class UUserWidget* SliderWidget, const int32& UpdatedValue, bool bShouldBeActive);
	void OnSliderIntegralValueChanged(class FName PropertyName, int32 NewIntegralValue, double NewSliderValue);
	void OnSliderPropertyAdded(class UUserWidget* SliderWidget, const class FName& PropertyName, const class FText& PropertyLocName, const class FText& PropertyTooltip, const TSoftObjectPtr<class UTexture2D>& TooltipTexture, const struct FMissionBuilderSliderData& UISettings, float DefaultValue, const bool bIsModified, const bool bUseUndefined);
	void OnSliderPropertyHover(const class FText& ToolTip, TSoftObjectPtr<class UTexture2D> TooltipTexture, class UW_MissionBuilderPropertyContainer_C* Property);
	void OnSliderResetToDefault(class UUserWidget* PropertyContentWidget, bool bUseUndefined);
	void OnStepSliderHovered(const class FText& ToolTip, TSoftObjectPtr<class UTexture2D> TooltipTexture, class UW_MissionBuilderPropertyContainer_C* Property);
	void OnStepSliderPropertyAdded(class UUserWidget* SliderWidget, const class FName& PropertyName, const class FText& PropertyLocName, const class FText& PropertyTooltip, const TSoftObjectPtr<class UTexture2D>& TooltipTexture, const struct FMissionBuilderSliderData& UISettings, int32 DefaultValue, const bool bIsModified, const bool bUseUndefined);
	void OnStepSliderPropertyUpdated(class UUserWidget* SliderWidget, const int32& UpdatedValue, bool bShouldBeActive);
	void OnStepSliderResetToDefault(class UUserWidget* PropertyContentWidget, bool bUseUndefined);
	void OnStepSliderValueChanged(class FName ProperyID, const class FText& ValueString, int32 ValueIndex);
	void ResetToDefaultBP(class UUserWidget* PropertyWidget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilderProperties_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilderProperties_C")
	}
	static class UW_MissionBuilderProperties_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilderProperties_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilderProperties_C;

}

