#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_CheckBox

#include "Basic.hpp"

#include "W_MissionBuilder_CheckBox_classes.hpp"
#include "W_MissionBuilder_CheckBox_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_CheckBox.W_MissionBuilder_CheckBox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_CheckBox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckBox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_CheckBox.W_MissionBuilder_CheckBox_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bNewCheckState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckBox_C::CustomEvent(bool bNewCheckState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckBox_C", "CustomEvent");

	Params::W_MissionBuilder_CheckBox_C_CustomEvent Parms{};

	Parms.bNewCheckState = bNewCheckState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckBox.W_MissionBuilder_CheckBox_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_CheckBox_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckBox_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_CheckBox.W_MissionBuilder_CheckBox_C.ExecuteUbergraph_W_MissionBuilder_CheckBox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckBox_C::ExecuteUbergraph_W_MissionBuilder_CheckBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckBox_C", "ExecuteUbergraph_W_MissionBuilder_CheckBox");

	Params::W_MissionBuilder_CheckBox_C_ExecuteUbergraph_W_MissionBuilder_CheckBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckBox.W_MissionBuilder_CheckBox_C.OnButtonHovered
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckBox_C::OnButtonHovered(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckBox_C", "OnButtonHovered");

	Params::W_MissionBuilder_CheckBox_C_OnButtonHovered Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckBox.W_MissionBuilder_CheckBox_C.SetUndefined
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsUndefined                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckBox_C::SetUndefined(bool IsUndefined)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckBox_C", "SetUndefined");

	Params::W_MissionBuilder_CheckBox_C_SetUndefined Parms{};

	Parms.IsUndefined = IsUndefined;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckBox.W_MissionBuilder_CheckBox_C.UpdateCheckboxCMB
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShouldBeSelected                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckBox_C::UpdateCheckboxCMB(bool bShouldBeSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckBox_C", "UpdateCheckboxCMB");

	Params::W_MissionBuilder_CheckBox_C_UpdateCheckboxCMB Parms{};

	Parms.bShouldBeSelected = bShouldBeSelected;

	UObject::ProcessEvent(Func, &Parms);
}

}

