#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilderPropertyContainer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "ReadyOrNot_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C
// 0x0108 (0x03D0 - 0x02C8)
class UW_MissionBuilderPropertyContainer_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_76;                                         // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             Dependents;                                        // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HB_Dependents;                                     // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 img_DependentLine;                                 // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               MainOverlay;                                       // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             PropertyContent;                                   // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ResetToDefaultBtn;                                 // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                UndefinedButton;                                   // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ValueChangedIndicator;                             // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_SettingLabel_C*                      W_PropertyLabel;                                   // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   InputBindText;                                     // 0x0320(0x0018)(Edit, BlueprintVisible)
	bool                                          bDependentsVisible;                                // 0x0338(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bDesignTime;                                       // 0x0339(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33A[0x6];                                      // 0x033A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   InputBindText_PS5Variant;                          // 0x0340(0x0018)(Edit, BlueprintVisible)
	struct FDataTableRowHandle                    Data;                                              // 0x0358(0x0010)(Edit, BlueprintVisible, NoDestructor)
	TMulticastInlineDelegate<void(class FText ToolTip, TSoftObjectPtr<class UTexture2D> TooltipTexture, class UW_MissionBuilderPropertyContainer_C* Property)> OnPropertyHover; // 0x0368(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FText                                   MBTooltip;                                         // 0x0378(0x0018)(Edit, BlueprintVisible)
	TSoftObjectPtr<class UTexture2D>              MBTooltipTexture;                                  // 0x0390(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UUserWidget* PropertyContentWidget, bool bUseUndefined)> OnResetToDefault; // 0x03B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          bUseUndefined;                                     // 0x03C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bResetVisible;                                     // 0x03C9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__W_MissionBuilderPropertyContainer_ResetToDefaultBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__W_MissionBuilderPropertyContainer_UndefinedButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void CallUndefinedOnProperty();
	void Construct();
	void DisplayDependents(bool ShowDependents);
	void ExecuteUbergraph_W_MissionBuilderPropertyContainer(int32 EntryPoint);
	void GetPropertyWidget(class UUserWidget** PropertyWidget);
	void OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void PreConstruct(bool IsDesignTime);
	void ResetToDefault();
	void SetInitialFocus();
	void SetPropertyName(const class FText& PropertyName);
	void SetShouldBeUsed(bool bShouldBeUsed, bool bIncludeReset);
	void SetUndefined(bool bShouldBeUndefined, bool bIsModified);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilderPropertyContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilderPropertyContainer_C")
	}
	static class UW_MissionBuilderPropertyContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilderPropertyContainer_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilderPropertyContainer_C;

}

