#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionDifficultySelection

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_MissionSelectionDifficultySelection.W_MissionBuilder_MissionSelectionDifficultySelection_C
// 0x0040 (0x0308 - 0x02C8)
class UW_MissionBuilder_MissionSelectionDifficultySelection_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UW_OnOffButton_C*                       Casual;                                            // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_OnOffButton_C*                       Hard;                                              // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_OnOffButton_C*                       Standard;                                          // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FName                                   PropertyName;                                      // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class FName PropertyName, EMissionBuilderDifficultyPropertyValues NewDifficultyValue)> OnDifficultyValueChanged; // 0x02F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	EMissionBuilderDifficultyPropertyValues       SelectedValue;                                     // 0x0300(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsUndefined;                                      // 0x0301(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__W_MissionBuilder_DifficultyButtons_Casual_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void BndEvt__W_MissionBuilder_DifficultyButtons_Hard_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature();
	void BndEvt__W_MissionBuilder_DifficultyButtons_Standard_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_W_MissionBuilder_MissionSelectionDifficultySelection(int32 EntryPoint);
	void GetValue(EMissionBuilderDifficultyPropertyValues* SelectedDifficulty);
	void PreConstruct(bool IsDesignTime);
	void SetDefaultValue(EMissionBuilderDifficultyPropertyValues DefaultValue);
	void SetUndefined(bool IsUndefined);
	void SetValue(EMissionBuilderDifficultyPropertyValues NewValue);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_MissionSelectionDifficultySelection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_MissionSelectionDifficultySelection_C")
	}
	static class UW_MissionBuilder_MissionSelectionDifficultySelection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_MissionSelectionDifficultySelection_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_MissionSelectionDifficultySelection_C;

}

