#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionDifficultySelection

#include "Basic.hpp"

#include "ReadyOrNot_structs.hpp"


namespace SDK::Params
{

// Function W_MissionBuilder_MissionSelectionDifficultySelection.W_MissionBuilder_MissionSelectionDifficultySelection_C.ExecuteUbergraph_W_MissionBuilder_MissionSelectionDifficultySelection
// 0x0008 (0x0008 - 0x0000)
struct W_MissionBuilder_MissionSelectionDifficultySelection_C_ExecuteUbergraph_W_MissionBuilder_MissionSelectionDifficultySelection final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_MissionSelectionDifficultySelection_C_ExecuteUbergraph_W_MissionBuilder_MissionSelectionDifficultySelection;

// Function W_MissionBuilder_MissionSelectionDifficultySelection.W_MissionBuilder_MissionSelectionDifficultySelection_C.GetValue
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilder_MissionSelectionDifficultySelection_C_GetValue final
{
public:
	EMissionBuilderDifficultyPropertyValues       SelectedDifficulty;                                // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_MissionSelectionDifficultySelection_C_GetValue;

// Function W_MissionBuilder_MissionSelectionDifficultySelection.W_MissionBuilder_MissionSelectionDifficultySelection_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilder_MissionSelectionDifficultySelection_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_MissionSelectionDifficultySelection_C_PreConstruct;

// Function W_MissionBuilder_MissionSelectionDifficultySelection.W_MissionBuilder_MissionSelectionDifficultySelection_C.SetDefaultValue
// 0x0002 (0x0002 - 0x0000)
struct W_MissionBuilder_MissionSelectionDifficultySelection_C_SetDefaultValue final
{
public:
	EMissionBuilderDifficultyPropertyValues       DefaultValue;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_MissionSelectionDifficultySelection_C_SetDefaultValue;

// Function W_MissionBuilder_MissionSelectionDifficultySelection.W_MissionBuilder_MissionSelectionDifficultySelection_C.SetUndefined
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilder_MissionSelectionDifficultySelection_C_SetUndefined final
{
public:
	bool                                          IsUndefined;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_MissionSelectionDifficultySelection_C_SetUndefined;

// Function W_MissionBuilder_MissionSelectionDifficultySelection.W_MissionBuilder_MissionSelectionDifficultySelection_C.SetValue
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilder_MissionSelectionDifficultySelection_C_SetValue final
{
public:
	EMissionBuilderDifficultyPropertyValues       NewValue;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_MissionSelectionDifficultySelection_C_SetValue;

}

