#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionMapItem

#include "Basic.hpp"

#include "W_MissionBuilder_MissionSelectionMapItem_classes.hpp"
#include "W_MissionBuilder_MissionSelectionMapItem_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionMapItem_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "BP_OnItemExpansionChanged");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "BP_OnItemSelectionChanged");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionMapItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapItem");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.Hover
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHovered_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::Hover(bool IsHovered_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "Hover");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_Hover Parms{};

	Parms.IsHovered_0 = IsHovered_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.InitializeLevelButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    LevelID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FText&                      LevelName                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// TSoftObjectPtr<class UTexture2D>        LevelImage                                             (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    bIsLocked                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::InitializeLevelButton(const class FString& LevelID, const class FText& LevelName, TSoftObjectPtr<class UTexture2D> LevelImage, bool bIsLocked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "InitializeLevelButton");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_InitializeLevelButton Parms{};

	Parms.LevelID = std::move(LevelID);
	Parms.LevelName = std::move(LevelName);
	Parms.LevelImage = LevelImage;
	Parms.bIsLocked = bIsLocked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "OnListItemObjectSet");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.Select
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::Select(bool IsSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "Select");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_Select Parms{};

	Parms.IsSelected_0 = IsSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.SetData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    LevelID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    IsLocked_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLevelDataLookupTable&     Data                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    NotOwned                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::SetData(const class FString& LevelID, bool IsLocked_0, const struct FLevelDataLookupTable& Data, bool NotOwned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "SetData");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_SetData Parms{};

	Parms.LevelID = std::move(LevelID);
	Parms.IsLocked_0 = IsLocked_0;
	Parms.Data = std::move(Data);
	Parms.NotOwned = NotOwned;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.SetHover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Hovered                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::SetHover(bool Hovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "SetHover");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_SetHover Parms{};

	Parms.Hovered = Hovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapItem.W_MissionBuilder_MissionSelectionMapItem_C.SetSelect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapItem_C::SetSelect(bool bSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapItem_C", "SetSelect");

	Params::W_MissionBuilder_MissionSelectionMapItem_C_SetSelect Parms{};

	Parms.bSelected = bSelected;

	UObject::ProcessEvent(Func, &Parms);
}

}

