#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionEnd_PVP

#include "Basic.hpp"

#include "CommonInput_structs.hpp"
#include "Engine_structs.hpp"
#include "ReadyOrNot_structs.hpp"
#include "ReadyOrNot_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionEnd_PVP.W_MissionEnd_PVP_C
// 0x0040 (0x04C0 - 0x0480)
class UW_MissionEnd_PVP_C final : public UMissionEndPvPWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0480(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                BlueTeamWinBackground;                             // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_InputActionButton_C*                 ContinueBtn;                                       // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                RedTeamWinBackground;                              // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlockBlueTeamScore;                            // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlockRedTeamScore;                             // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       VictoryTextHeader;                                 // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       VictoryTextResult;                                 // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BackPage(bool* Handled);
	void BndEvt__W_MissionEnd_PVP_ReadyBtn_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BP_OnActivated();
	bool BP_OnHandleBackAction();
	void ChangePage(class FName PageName);
	void Construct();
	void ExecuteUbergraph_W_MissionEnd_PVP(int32 EntryPoint);
	void FocusOnDefaultWidget();
	void Hide(double Delay, bool Collapse);
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnInitialized();
	void OnInputMethodChanged(ECommonInputType bNewInputType);
	void OnMissionDataRefreshed();
	void PreConstruct(bool IsDesignTime);
	void Reveal(double Delay);
	void SetInputMode(bool IsGamepad);

	class UWidget* BP_GetDesiredFocusTarget() const;
	void GetFocusTarget(class UWidget** Focus) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionEnd_PVP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionEnd_PVP_C")
	}
	static class UW_MissionEnd_PVP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionEnd_PVP_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionEnd_PVP_C;

}

