#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_DifficultySelector

#include "Basic.hpp"

#include "W_MissionBuilder_DifficultySelector_classes.hpp"
#include "W_MissionBuilder_DifficultySelector_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.BndEvt__W_MissionBuilder_DifficultySelector_NextGamepadTabButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultySelector_C::BndEvt__W_MissionBuilder_DifficultySelector_NextGamepadTabButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "BndEvt__W_MissionBuilder_DifficultySelector_NextGamepadTabButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");

	Params::W_MissionBuilder_DifficultySelector_C_BndEvt__W_MissionBuilder_DifficultySelector_NextGamepadTabButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.BndEvt__W_MissionBuilder_DifficultySelector_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultySelector_C::BndEvt__W_MissionBuilder_DifficultySelector_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "BndEvt__W_MissionBuilder_DifficultySelector_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature");

	Params::W_MissionBuilder_DifficultySelector_C_BndEvt__W_MissionBuilder_DifficultySelector_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_DifficultySelector_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.ExecuteUbergraph_W_MissionBuilder_DifficultySelector
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultySelector_C::ExecuteUbergraph_W_MissionBuilder_DifficultySelector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "ExecuteUbergraph_W_MissionBuilder_DifficultySelector");

	Params::W_MissionBuilder_DifficultySelector_C_ExecuteUbergraph_W_MissionBuilder_DifficultySelector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.Navigate Left
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultySelector_C::Navigate_Left(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "Navigate Left");

	Params::W_MissionBuilder_DifficultySelector_C_Navigate_Left Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.Navigate Right
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultySelector_C::Navigate_Right(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "Navigate Right");

	Params::W_MissionBuilder_DifficultySelector_C_Navigate_Right Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.OnPreviewMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UW_MissionBuilder_DifficultySelector_C::OnPreviewMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "OnPreviewMouseButtonDown");

	Params::W_MissionBuilder_DifficultySelector_C_OnPreviewMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultySelector_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "PreConstruct");

	Params::W_MissionBuilder_DifficultySelector_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_DifficultySelector.W_MissionBuilder_DifficultySelector_C.UpdateSelection
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_CMBCheckSlider_CheckArea_C*    SelectedCheckArea                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultySelector_C::UpdateSelection(class UW_CMBCheckSlider_CheckArea_C* SelectedCheckArea)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultySelector_C", "UpdateSelection");

	Params::W_MissionBuilder_DifficultySelector_C_UpdateSelection Parms{};

	Parms.SelectedCheckArea = SelectedCheckArea;

	UObject::ProcessEvent(Func, &Parms);
}

}

