#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilderPropertyContainer

#include "Basic.hpp"

#include "W_MissionBuilderPropertyContainer_classes.hpp"
#include "W_MissionBuilderPropertyContainer_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.BndEvt__W_MissionBuilderPropertyContainer_ResetToDefaultBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_MissionBuilderPropertyContainer_C::BndEvt__W_MissionBuilderPropertyContainer_ResetToDefaultBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "BndEvt__W_MissionBuilderPropertyContainer_ResetToDefaultBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.BndEvt__W_MissionBuilderPropertyContainer_UndefinedButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_MissionBuilderPropertyContainer_C::BndEvt__W_MissionBuilderPropertyContainer_UndefinedButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "BndEvt__W_MissionBuilderPropertyContainer_UndefinedButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.CallUndefinedOnProperty
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MissionBuilderPropertyContainer_C::CallUndefinedOnProperty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "CallUndefinedOnProperty");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilderPropertyContainer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.DisplayDependents
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShowDependents                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPropertyContainer_C::DisplayDependents(bool ShowDependents)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "DisplayDependents");

	Params::W_MissionBuilderPropertyContainer_C_DisplayDependents Parms{};

	Parms.ShowDependents = ShowDependents;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.ExecuteUbergraph_W_MissionBuilderPropertyContainer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPropertyContainer_C::ExecuteUbergraph_W_MissionBuilderPropertyContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "ExecuteUbergraph_W_MissionBuilderPropertyContainer");

	Params::W_MissionBuilderPropertyContainer_C_ExecuteUbergraph_W_MissionBuilderPropertyContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.GetPropertyWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget**                     PropertyWidget                                         (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPropertyContainer_C::GetPropertyWidget(class UUserWidget** PropertyWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "GetPropertyWidget");

	Params::W_MissionBuilderPropertyContainer_C_GetPropertyWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PropertyWidget != nullptr)
		*PropertyWidget = Parms.PropertyWidget;
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_MissionBuilderPropertyContainer_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "OnMouseEnter");

	Params::W_MissionBuilderPropertyContainer_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_MissionBuilderPropertyContainer_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "OnMouseLeave");

	Params::W_MissionBuilderPropertyContainer_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPropertyContainer_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "PreConstruct");

	Params::W_MissionBuilderPropertyContainer_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.ResetToDefault
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MissionBuilderPropertyContainer_C::ResetToDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "ResetToDefault");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.SetInitialFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MissionBuilderPropertyContainer_C::SetInitialFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "SetInitialFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.SetPropertyName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      PropertyName                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_MissionBuilderPropertyContainer_C::SetPropertyName(const class FText& PropertyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "SetPropertyName");

	Params::W_MissionBuilderPropertyContainer_C_SetPropertyName Parms{};

	Parms.PropertyName = std::move(PropertyName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.SetShouldBeUsed
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShouldBeUsed                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIncludeReset                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPropertyContainer_C::SetShouldBeUsed(bool bShouldBeUsed, bool bIncludeReset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "SetShouldBeUsed");

	Params::W_MissionBuilderPropertyContainer_C_SetShouldBeUsed Parms{};

	Parms.bShouldBeUsed = bShouldBeUsed;
	Parms.bIncludeReset = bIncludeReset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPropertyContainer.W_MissionBuilderPropertyContainer_C.SetUndefined
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShouldBeUndefined                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsModified                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPropertyContainer_C::SetUndefined(bool bShouldBeUndefined, bool bIsModified)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPropertyContainer_C", "SetUndefined");

	Params::W_MissionBuilderPropertyContainer_C_SetUndefined Parms{};

	Parms.bShouldBeUndefined = bShouldBeUndefined;
	Parms.bIsModified = bIsModified;

	UObject::ProcessEvent(Func, &Parms);
}

}

