#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_StandardSlider

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_MissionBuilder_StandardSlider.W_MissionBuilder_StandardSlider_C.CustomEvent
// 0x0010 (0x0010 - 0x0000)
struct W_MissionBuilder_StandardSlider_C_CustomEvent final
{
public:
	int32                                         NewIntegerValue;                                   // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        NewSliderValue;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_StandardSlider_C_CustomEvent;

// Function W_MissionBuilder_StandardSlider.W_MissionBuilder_StandardSlider_C.CustomEvent_0
// 0x0010 (0x0010 - 0x0000)
struct W_MissionBuilder_StandardSlider_C_CustomEvent_0 final
{
public:
	double                                        NewFloatValue;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        NewSliderValue;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_StandardSlider_C_CustomEvent_0;

// Function W_MissionBuilder_StandardSlider.W_MissionBuilder_StandardSlider_C.ExecuteUbergraph_W_MissionBuilder_StandardSlider
// 0x0068 (0x0068 - 0x0000)
struct W_MissionBuilder_StandardSlider_C_ExecuteUbergraph_W_MissionBuilder_StandardSlider final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_NewIntegerValue;                // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_NewSliderValue_1;               // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        K2Node_CustomEvent_NewFloatValue;                  // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_CustomEvent_NewSliderValue;                 // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(double NewFloatValue, double NewSliderValue)> K2Node_CreateDelegate_OutputDelegate_2; // 0x0048(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 NewIntegerValue, double NewSliderValue)> K2Node_CreateDelegate_OutputDelegate_3; // 0x0058(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_StandardSlider_C_ExecuteUbergraph_W_MissionBuilder_StandardSlider;

// Function W_MissionBuilder_StandardSlider.W_MissionBuilder_StandardSlider_C.SetMaximum
// 0x0010 (0x0010 - 0x0000)
struct W_MissionBuilder_StandardSlider_C_SetMaximum final
{
public:
	int32                                         NewMaximum;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_SetIntegralValue_NewValue;                // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SetIntegralValue_NewValue_1;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_StandardSlider_C_SetMaximum;

// Function W_MissionBuilder_StandardSlider.W_MissionBuilder_StandardSlider_C.SetUndefined
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilder_StandardSlider_C_SetUndefined final
{
public:
	bool                                          IsUndefined;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilder_StandardSlider_C_SetUndefined;

}

