#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_StandardSlider

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "W_StandardSlider_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_StandardSlider.W_MissionBuilder_StandardSlider_C
// 0x0F90 (0x13D0 - 0x0440)
class UW_MissionBuilder_StandardSlider_C final : public UW_StandardSlider_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_MissionBuilder_StandardSlider_C;  // 0x0440(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   PropertyName;                                      // 0x0448(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class FName PropertyName, int32 NewIntegralValue, double NewSliderValue)> OnMissionBuilderIntegralValueChanged; // 0x0450(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class FName PropertyName, double NewFloatValue, double NewSliderValue)> OnMissionBuilderFloatValueChanged; // 0x0460(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FSliderStyle                           SliderStyleUndefined;                              // 0x0470(0x0500)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSliderStyle                           SliderStyleActive;                                 // 0x0970(0x0500)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bIsUndefined;                                      // 0x0E70(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E71[0xF];                                      // 0x0E71(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FProgressBarStyle                      ProgressBarUndefined;                              // 0x0E80(0x0290)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FProgressBarStyle                      ProgressBarActive;                                 // 0x1110(0x0290)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          MouseCapture;                                      // 0x13A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13A1[0x7];                                     // 0x13A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MouseCapturedFloat;                                // 0x13A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MouseCapturedInteger;                              // 0x13B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13B4[0x4];                                     // 0x13B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MouseCapturedSliderValue;                          // 0x13B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          MouseCaptureTypeFloat;                             // 0x13C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void CustomEvent(int32 NewIntegerValue, double NewSliderValue);
	void CustomEvent_0(double NewFloatValue, double NewSliderValue);
	void ExecuteUbergraph_W_MissionBuilder_StandardSlider(int32 EntryPoint);
	void OnSliderMouseCaptureBegin();
	void OnSliderMouseCaptureEnd();
	void SetMaximum(int32 NewMaximum);
	void SetUndefined(bool IsUndefined);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_StandardSlider_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_StandardSlider_C")
	}
	static class UW_MissionBuilder_StandardSlider_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_StandardSlider_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_StandardSlider_C;

}

