#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionScreen

#include "Basic.hpp"

#include "W_MissionBuilder_MissionSelectionScreen_classes.hpp"
#include "W_MissionBuilder_MissionSelectionScreen_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.BndEvt__W_MissionBuilder_MissionSelectionScreen_NextGamepadTabButton_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::BndEvt__W_MissionBuilder_MissionSelectionScreen_NextGamepadTabButton_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "BndEvt__W_MissionBuilder_MissionSelectionScreen_NextGamepadTabButton_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionScreen_C_BndEvt__W_MissionBuilder_MissionSelectionScreen_NextGamepadTabButton_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_1_SimpleListItemEventDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_1_SimpleListItemEventDynamic__DelegateSignature(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_1_SimpleListItemEventDynamic__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionScreen_C_BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_1_SimpleListItemEventDynamic__DelegateSignature Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_2_OnListItemSelectionChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_2_OnListItemSelectionChangedDynamic__DelegateSignature(class UObject* Item, bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_2_OnListItemSelectionChangedDynamic__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionScreen_C_BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_2_OnListItemSelectionChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_9_OnItemIsHoveredChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_9_OnItemIsHoveredChangedDynamic__DelegateSignature(class UObject* Item, bool bIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_9_OnItemIsHoveredChangedDynamic__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionScreen_C_BndEvt__W_MissionBuilder_MissionSelectionScreen_PresetsListView_K2Node_ComponentBoundEvent_9_OnItemIsHoveredChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsHovered = bIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.BndEvt__W_MissionBuilder_MissionSelectionScreen_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UW_Button_C*                      Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::BndEvt__W_MissionBuilder_MissionSelectionScreen_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature(class UW_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "BndEvt__W_MissionBuilder_MissionSelectionScreen_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionScreen_C_BndEvt__W_MissionBuilder_MissionSelectionScreen_PreviousGamepadTabButton_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.BndEvt__W_MissionBuilderPresets_MissionBuilder_PageWrapper_K2Node_ComponentBoundEvent_0_OnFooterButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    ButtonId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::BndEvt__W_MissionBuilderPresets_MissionBuilder_PageWrapper_K2Node_ComponentBoundEvent_0_OnFooterButtonClicked__DelegateSignature(const class FString& ButtonId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "BndEvt__W_MissionBuilderPresets_MissionBuilder_PageWrapper_K2Node_ComponentBoundEvent_0_OnFooterButtonClicked__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionScreen_C_BndEvt__W_MissionBuilderPresets_MissionBuilder_PageWrapper_K2Node_ComponentBoundEvent_0_OnFooterButtonClicked__DelegateSignature Parms{};

	Parms.ButtonId = std::move(ButtonId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.ChangeMapPreviewBackground
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       MapImage                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::ChangeMapPreviewBackground(class UTexture2D* MapImage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "ChangeMapPreviewBackground");

	Params::W_MissionBuilder_MissionSelectionScreen_C_ChangeMapPreviewBackground Parms{};

	Parms.MapImage = MapImage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionScreen_C::CustomEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "CustomEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.DeleteSelectedPreset
// (BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionScreen_C::DeleteSelectedPreset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "DeleteSelectedPreset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.ExecuteUbergraph_W_MissionBuilder_MissionSelectionScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::ExecuteUbergraph_W_MissionBuilder_MissionSelectionScreen(int32 EntryPoint_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "ExecuteUbergraph_W_MissionBuilder_MissionSelectionScreen");

	Params::W_MissionBuilder_MissionSelectionScreen_C_ExecuteUbergraph_W_MissionBuilder_MissionSelectionScreen Parms{};

	Parms.EntryPoint_0 = EntryPoint_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.InitializeEntryPoints
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FEntryPoint>&             EntryPoints                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_MissionBuilder_MissionSelectionScreen_C::InitializeEntryPoints(TArray<struct FEntryPoint>& EntryPoints)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "InitializeEntryPoints");

	Params::W_MissionBuilder_MissionSelectionScreen_C_InitializeEntryPoints Parms{};

	Parms.EntryPoints = std::move(EntryPoints);

	UObject::ProcessEvent(Func, &Parms);

	EntryPoints = std::move(Parms.EntryPoints);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.InitializeNewCampaign
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      CampaignName                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      CampaignTitle                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_MissionBuilder_MissionSelectionScreen_C::InitializeNewCampaign(const class FName& CampaignName, const class FText& CampaignTitle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "InitializeNewCampaign");

	Params::W_MissionBuilder_MissionSelectionScreen_C_InitializeNewCampaign Parms{};

	Parms.CampaignName = CampaignName;
	Parms.CampaignTitle = std::move(CampaignTitle);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.InitializeNewLevel
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      CampaignName                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    LevelName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FLevelDataLookupTable&     LevelData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bIsLocked                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bNotOwned                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::InitializeNewLevel(const class FName& CampaignName, const class FString& LevelName, const struct FLevelDataLookupTable& LevelData, bool bIsLocked, bool bNotOwned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "InitializeNewLevel");

	Params::W_MissionBuilder_MissionSelectionScreen_C_InitializeNewLevel Parms{};

	Parms.CampaignName = CampaignName;
	Parms.LevelName = std::move(LevelName);
	Parms.LevelData = std::move(LevelData);
	Parms.bIsLocked = bIsLocked;
	Parms.bNotOwned = bNotOwned;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.On Entry Point Clicked
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_MissionSelect_EntryPoint_C*    Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::On_Entry_Point_Clicked(class UW_MissionSelect_EntryPoint_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "On Entry Point Clicked");

	Params::W_MissionBuilder_MissionSelectionScreen_C_On_Entry_Point_Clicked Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnAnimEnd
// (BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionScreen_C::OnAnimEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnAnimEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnCampaignSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_MissionBuilder_MissionSelectionMapCampaignSection_C*Campaign                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::OnCampaignSelected(class UW_MissionBuilder_MissionSelectionMapCampaignSection_C* Campaign)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnCampaignSelected");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnCampaignSelected Parms{};

	Parms.Campaign = Campaign;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnDeleteCancelClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStandardModal*                   CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::OnDeleteCancelClicked(class UStandardModal* CallingModal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnDeleteCancelClicked");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnDeleteCancelClicked Parms{};

	Parms.CallingModal = CallingModal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnDeleteOkClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_StandardModal_C*               CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FText&                      TextEntry                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_MissionBuilder_MissionSelectionScreen_C::OnDeleteOkClicked(class UW_StandardModal_C* CallingModal, const class FText& TextEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnDeleteOkClicked");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnDeleteOkClicked Parms{};

	Parms.CallingModal = CallingModal;
	Parms.TextEntry = std::move(TextEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnDifficultyChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ProperyID                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      ValueString                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   ValueIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::OnDifficultyChanged(class FName ProperyID, const class FText& ValueString, int32 ValueIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnDifficultyChanged");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnDifficultyChanged Parms{};

	Parms.ProperyID = ProperyID;
	Parms.ValueString = std::move(ValueString);
	Parms.ValueIndex = ValueIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnFavouriteSet
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PresetIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFavourite                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::OnFavouriteSet(int32 PresetIndex, bool bFavourite)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnFavouriteSet");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnFavouriteSet Parms{};

	Parms.PresetIndex = PresetIndex;
	Parms.bFavourite = bFavourite;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnInput Changed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        bNewInputType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::OnInput_Changed(ECommonInputType bNewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnInput Changed");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnInput_Changed Parms{};

	Parms.bNewInputType = bNewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnMapDescriptionUpdated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_MissionBuilder_MapSelectionListItemEntry_C*SelectedMap                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::OnMapDescriptionUpdated(class UBP_MissionBuilder_MapSelectionListItemEntry_C* SelectedMap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnMapDescriptionUpdated");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnMapDescriptionUpdated Parms{};

	Parms.SelectedMap = SelectedMap;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnPresetNameCommitted
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PresetIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      PresetName                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_MissionBuilder_MissionSelectionScreen_C::OnPresetNameCommitted(int32 PresetIndex, const class FText& PresetName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnPresetNameCommitted");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnPresetNameCommitted Parms{};

	Parms.PresetIndex = PresetIndex;
	Parms.PresetName = std::move(PresetName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnShareCodeConfirmCancelClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStandardModal*                   CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::OnShareCodeConfirmCancelClicked(class UStandardModal* CallingModal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnShareCodeConfirmCancelClicked");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnShareCodeConfirmCancelClicked Parms{};

	Parms.CallingModal = CallingModal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnShareCodeConfirmOkClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_StandardModal_C*               CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FText&                      TextEntry                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_MissionBuilder_MissionSelectionScreen_C::OnShareCodeConfirmOkClicked(class UW_StandardModal_C* CallingModal, const class FText& TextEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnShareCodeConfirmOkClicked");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnShareCodeConfirmOkClicked Parms{};

	Parms.CallingModal = CallingModal;
	Parms.TextEntry = std::move(TextEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.OnShareCodeOkClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_StandardModal_C*               CallingModal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const class FText&                      TextEntry                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_MissionBuilder_MissionSelectionScreen_C::OnShareCodeOkClicked(class UW_StandardModal_C* CallingModal, const class FText& TextEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "OnShareCodeOkClicked");

	Params::W_MissionBuilder_MissionSelectionScreen_C_OnShareCodeOkClicked Parms{};

	Parms.CallingModal = CallingModal;
	Parms.TextEntry = std::move(TextEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.SetEnableForScroll
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UW_MissionBuilder_MissionSelectionScreen_C::SetEnableForScroll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "SetEnableForScroll");

	Params::W_MissionBuilder_MissionSelectionScreen_C_SetEnableForScroll Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.SetInitialFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionScreen_C::SetInitialFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "SetInitialFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.SetListActive
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::SetListActive(bool IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "SetListActive");

	Params::W_MissionBuilder_MissionSelectionScreen_C_SetListActive Parms{};

	Parms.IsActive = IsActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.ShowEntryPoints
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::ShowEntryPoints(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "ShowEntryPoints");

	Params::W_MissionBuilder_MissionSelectionScreen_C_ShowEntryPoints Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.ShowHashScreen
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::ShowHashScreen(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "ShowHashScreen");

	Params::W_MissionBuilder_MissionSelectionScreen_C_ShowHashScreen Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.SwitchToMissionMapsList
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWithAnimation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::SwitchToMissionMapsList(bool bWithAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "SwitchToMissionMapsList");

	Params::W_MissionBuilder_MissionSelectionScreen_C_SwitchToMissionMapsList Parms{};

	Parms.bWithAnimation = bWithAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.SwitchToMissionVersionsList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWithAnimation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::SwitchToMissionVersionsList(bool bWithAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "SwitchToMissionVersionsList");

	Params::W_MissionBuilder_MissionSelectionScreen_C_SwitchToMissionVersionsList Parms{};

	Parms.bWithAnimation = bWithAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.Update Mission Description
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLevelDataLookupTable&     LevelData                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    IsLocked                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsFullSlots                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    NotOwned                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   UsedSlots                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionScreen_C::Update_Mission_Description(const struct FLevelDataLookupTable& LevelData, bool IsLocked, bool IsFullSlots, bool NotOwned, int32 UsedSlots)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "Update Mission Description");

	Params::W_MissionBuilder_MissionSelectionScreen_C_Update_Mission_Description Parms{};

	Parms.LevelData = std::move(LevelData);
	Parms.IsLocked = IsLocked;
	Parms.IsFullSlots = IsFullSlots;
	Parms.NotOwned = NotOwned;
	Parms.UsedSlots = UsedSlots;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionScreen.W_MissionBuilder_MissionSelectionScreen_C.UpdateAfterRename
// (BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionScreen_C::UpdateAfterRename()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionScreen_C", "UpdateAfterRename");

	UObject::ProcessEvent(Func, nullptr);
}

}

