#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_CheckSlider

#include "Basic.hpp"

#include "W_MissionBuilder_CheckSlider_classes.hpp"
#include "W_MissionBuilder_CheckSlider_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_CheckSlider_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.ExecuteUbergraph_W_MissionBuilder_CheckSlider
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::ExecuteUbergraph_W_MissionBuilder_CheckSlider(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "ExecuteUbergraph_W_MissionBuilder_CheckSlider");

	Params::W_MissionBuilder_CheckSlider_C_ExecuteUbergraph_W_MissionBuilder_CheckSlider Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.GetSelection
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  SelectedIndex                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::GetSelection(int32* SelectedIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "GetSelection");

	Params::W_MissionBuilder_CheckSlider_C_GetSelection Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SelectedIndex != nullptr)
		*SelectedIndex = Parms.SelectedIndex;
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.Navigate Left
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::Navigate_Left(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "Navigate Left");

	Params::W_MissionBuilder_CheckSlider_C_Navigate_Left Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.Navigate Right
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::Navigate_Right(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "Navigate Right");

	Params::W_MissionBuilder_CheckSlider_C_Navigate_Right Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.OnPreviewMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UW_MissionBuilder_CheckSlider_C::OnPreviewMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "OnPreviewMouseButtonDown");

	Params::W_MissionBuilder_CheckSlider_C_OnPreviewMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "PreConstruct");

	Params::W_MissionBuilder_CheckSlider_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.SetSelection
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SelectedIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWithCallback                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::SetSelection(int32 SelectedIndex, bool bWithCallback)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "SetSelection");

	Params::W_MissionBuilder_CheckSlider_C_SetSelection Parms{};

	Parms.SelectedIndex = SelectedIndex;
	Parms.bWithCallback = bWithCallback;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.SetUndefined
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsUndefined                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::SetUndefined(bool IsUndefined)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "SetUndefined");

	Params::W_MissionBuilder_CheckSlider_C_SetUndefined Parms{};

	Parms.IsUndefined = IsUndefined;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckSlider.W_MissionBuilder_CheckSlider_C.UpdateSelection
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_CMBCheckSlider_CheckArea_C*    SelectedCheckArea                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    bWithCallback                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckSlider_C::UpdateSelection(class UW_CMBCheckSlider_CheckArea_C* SelectedCheckArea, bool bWithCallback)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckSlider_C", "UpdateSelection");

	Params::W_MissionBuilder_CheckSlider_C_UpdateSelection Parms{};

	Parms.SelectedCheckArea = SelectedCheckArea;
	Parms.bWithCallback = bWithCallback;

	UObject::ProcessEvent(Func, &Parms);
}

}

