#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionMapCampaignSection

#include "Basic.hpp"

#include "W_MissionBuilder_MissionSelectionMapCampaignSection_classes.hpp"
#include "W_MissionBuilder_MissionSelectionMapCampaignSection_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.AddLevel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    LevelID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FLevelDataLookupTable&     LevelData                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    bIsLocked                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bNotOwned                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::AddLevel(const class FString& LevelID, const struct FLevelDataLookupTable& LevelData, bool bIsLocked, bool bNotOwned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "AddLevel");

	Params::W_MissionBuilder_MissionSelectionMapCampaignSection_C_AddLevel Parms{};

	Parms.LevelID = std::move(LevelID);
	Parms.LevelData = std::move(LevelData);
	Parms.bIsLocked = bIsLocked;
	Parms.bNotOwned = bNotOwned;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_0_OnListItemSelectionChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsSelected_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_0_OnListItemSelectionChangedDynamic__DelegateSignature(class UObject* Item, bool bIsSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_0_OnListItemSelectionChangedDynamic__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionMapCampaignSection_C_BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_0_OnListItemSelectionChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsSelected_0 = bIsSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature(class UObject* Item, bool bIsHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionMapCampaignSection_C_BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature Parms{};

	Parms.Item = Item;
	Parms.bIsHovered = bIsHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UObject*                          Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature(class UObject* Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature");

	Params::W_MissionBuilder_MissionSelectionMapCampaignSection_C_BndEvt__W_MissionBuilder_MissionSelectionMapCampaignSection_CampaignMapList_K2Node_ComponentBoundEvent_2_SimpleListItemEventDynamic__DelegateSignature Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.DeselectMap
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::DeselectMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "DeselectMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapCampaignSection
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapCampaignSection(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapCampaignSection");

	Params::W_MissionBuilder_MissionSelectionMapCampaignSection_C_ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapCampaignSection Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapCampaignSection.W_MissionBuilder_MissionSelectionMapCampaignSection_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UW_MissionBuilder_MissionSelectionMapCampaignSection_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapCampaignSection_C", "OnFocusLost");

	Params::W_MissionBuilder_MissionSelectionMapCampaignSection_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}

}

