#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilderDescription

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilderDescription.W_MissionBuilderDescription_C
// 0x0000 (0x0418 - 0x0418)
class UW_MissionBuilderDescription_C final : public UCommonActivatableWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilderDescription_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilderDescription_C")
	}
	static class UW_MissionBuilderDescription_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilderDescription_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilderDescription_C;

}

