#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_CheckboxArrayElement

#include "Basic.hpp"

#include "W_MissionBuilder_CheckboxArrayElement_classes.hpp"
#include "W_MissionBuilder_CheckboxArrayElement_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_CheckboxArrayElement.W_MissionBuilder_CheckboxArrayElement_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_CheckboxArrayElement_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckboxArrayElement_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_CheckboxArrayElement.W_MissionBuilder_CheckboxArrayElement_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_CheckboxArrayElement_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckboxArrayElement_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_CheckboxArrayElement.W_MissionBuilder_CheckboxArrayElement_C.ExecuteUbergraph_W_MissionBuilder_CheckboxArrayElement
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckboxArrayElement_C::ExecuteUbergraph_W_MissionBuilder_CheckboxArrayElement(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckboxArrayElement_C", "ExecuteUbergraph_W_MissionBuilder_CheckboxArrayElement");

	Params::W_MissionBuilder_CheckboxArrayElement_C_ExecuteUbergraph_W_MissionBuilder_CheckboxArrayElement Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckboxArrayElement.W_MissionBuilder_CheckboxArrayElement_C.OnCheckboxOptionChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             PropertyName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    NewBoolValue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckboxArrayElement_C::OnCheckboxOptionChanged(class FName PropertyName, bool NewBoolValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckboxArrayElement_C", "OnCheckboxOptionChanged");

	Params::W_MissionBuilder_CheckboxArrayElement_C_OnCheckboxOptionChanged Parms{};

	Parms.PropertyName = PropertyName;
	Parms.NewBoolValue = NewBoolValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_CheckboxArrayElement.W_MissionBuilder_CheckboxArrayElement_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_CheckboxArrayElement_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_CheckboxArrayElement_C", "PreConstruct");

	Params::W_MissionBuilder_CheckboxArrayElement_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

