#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionListItem

#include "Basic.hpp"

#include "W_MissionBuilder_MissionSelectionListItem_classes.hpp"
#include "W_MissionBuilder_MissionSelectionListItem_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.BndEvt__W_MissionBuilder_MissionSelectionListItem_FavouriteButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UW_MissionBuilder_MissionSelectionListItem_C::BndEvt__W_MissionBuilder_MissionSelectionListItem_FavouriteButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "BndEvt__W_MissionBuilder_MissionSelectionListItem_FavouriteButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionListItem_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "BP_OnItemExpansionChanged");

	Params::W_MissionBuilder_MissionSelectionListItem_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "BP_OnItemSelectionChanged");

	Params::W_MissionBuilder_MissionSelectionListItem_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.CheckForLength
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_MissionBuilder_MissionSelectionListItem_C::CheckForLength(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "CheckForLength");

	Params::W_MissionBuilder_MissionSelectionListItem_C_CheckForLength Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionListItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.ExecuteUbergraph_W_MissionBuilder_MissionSelectionListItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::ExecuteUbergraph_W_MissionBuilder_MissionSelectionListItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "ExecuteUbergraph_W_MissionBuilder_MissionSelectionListItem");

	Params::W_MissionBuilder_MissionSelectionListItem_C_ExecuteUbergraph_W_MissionBuilder_MissionSelectionListItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.FavouritePressed
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionListItem_C::FavouritePressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "FavouritePressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.Hover
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHovered_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::Hover(bool IsHovered_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "Hover");

	Params::W_MissionBuilder_MissionSelectionListItem_C_Hover Parms{};

	Parms.IsHovered_0 = IsHovered_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.OnInputChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        bNewInputType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::OnInputChanged(ECommonInputType bNewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "OnInputChanged");

	Params::W_MissionBuilder_MissionSelectionListItem_C_OnInputChanged Parms{};

	Parms.bNewInputType = bNewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "OnListItemObjectSet");

	Params::W_MissionBuilder_MissionSelectionListItem_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.OnPresetNameCommitted
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::OnPresetNameCommitted(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "OnPresetNameCommitted");

	Params::W_MissionBuilder_MissionSelectionListItem_C_OnPresetNameCommitted Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.RenameSlot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionListItem_C::RenameSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "RenameSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.Select
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::Select(bool IsSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "Select");

	Params::W_MissionBuilder_MissionSelectionListItem_C_Select Parms{};

	Parms.IsSelected_0 = IsSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.SetData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    MissionMapName_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   Date_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMissionBuilderDifficultyPropertyValues Difficulty_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       MissionImage                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const class FString&                    MissionDescription_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::SetData(int32 Param_Index_0, const class FString& MissionMapName_0, int64 Date_0, EMissionBuilderDifficultyPropertyValues Difficulty_0, class UTexture2D* MissionImage, const class FString& MissionDescription_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "SetData");

	Params::W_MissionBuilder_MissionSelectionListItem_C_SetData Parms{};

	Parms.Param_Index_0 = Param_Index_0;
	Parms.MissionMapName_0 = std::move(MissionMapName_0);
	Parms.Date_0 = Date_0;
	Parms.Difficulty_0 = Difficulty_0;
	Parms.MissionImage = MissionImage;
	Parms.MissionDescription_0 = std::move(MissionDescription_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.SetHover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHover                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::SetHover(bool IsHover)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "SetHover");

	Params::W_MissionBuilder_MissionSelectionListItem_C_SetHover Parms{};

	Parms.IsHover = IsHover;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionListItem.W_MissionBuilder_MissionSelectionListItem_C.SetSelect
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionListItem_C::SetSelect(bool bSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionListItem_C", "SetSelect");

	Params::W_MissionBuilder_MissionSelectionListItem_C_SetSelect Parms{};

	Parms.bSelected = bSelected;

	UObject::ProcessEvent(Func, &Parms);
}

}

