#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilderPageBtn

#include "Basic.hpp"

#include "W_MissionBuilderPageBtn_classes.hpp"
#include "W_MissionBuilderPageBtn_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bNewCheckState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPageBtn_C::BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature(bool bNewCheckState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPageBtn_C", "BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature");

	Params::W_MissionBuilderPageBtn_C_BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature Parms{};

	Parms.bNewCheckState = bNewCheckState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.BndEvt__W_MissionBuilderCategoryBtn_W_CategoryButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UW_MissionBuilderPageBtn_C::BndEvt__W_MissionBuilderCategoryBtn_W_CategoryButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPageBtn_C", "BndEvt__W_MissionBuilderCategoryBtn_W_CategoryButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilderPageBtn_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPageBtn_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.ExecuteUbergraph_W_MissionBuilderPageBtn
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPageBtn_C::ExecuteUbergraph_W_MissionBuilderPageBtn(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPageBtn_C", "ExecuteUbergraph_W_MissionBuilderPageBtn");

	Params::W_MissionBuilderPageBtn_C_ExecuteUbergraph_W_MissionBuilderPageBtn Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPageBtn_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPageBtn_C", "PreConstruct");

	Params::W_MissionBuilderPageBtn_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.SetButtonSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilderPageBtn_C::SetButtonSelected(bool bSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPageBtn_C", "SetButtonSelected");

	Params::W_MissionBuilderPageBtn_C_SetButtonSelected Parms{};

	Parms.bSelected = bSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.SetButtonText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      CategoryText                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_MissionBuilderPageBtn_C::SetButtonText(const class FText& CategoryText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilderPageBtn_C", "SetButtonText");

	Params::W_MissionBuilderPageBtn_C_SetButtonText Parms{};

	Parms.CategoryText = std::move(CategoryText);

	UObject::ProcessEvent(Func, &Parms);
}

}

