#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionMapSection

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_MissionSelectionMapSection.W_MissionBuilder_MissionSelectionMapSection_C
// 0x0068 (0x0330 - 0x02C8)
class UW_MissionBuilder_MissionSelectionMapSection_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUniformGridPanel*                      MapsGrid;                                          // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_MissionSelectionMapItem_C* W_MissionBuilder_MissionSelectionMapItem;     // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_MissionSelectionMapItem_C* W_MissionBuilder_MissionSelectionMapItem_1;   // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_MissionSelectionMapItem_C* W_MissionBuilder_MissionSelectionMapItem_2;   // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_MissionSelectionMapItem_C* W_MissionBuilder_MissionSelectionMapItem_3;   // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FName                                   CampaignName;                                      // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentRow;                                        // 0x0300(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentColumn;                                     // 0x0304(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxColumnLevels;                                   // 0x0308(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_MissionBuilder_MissionSelectionMapItem_C* CurrentSelectedLevelButton;                   // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(const class FString& SelectedLevel, class UW_MissionBuilder_MissionSelectionMapItem_C* SelectedButton)> OnNewLevelSelected; // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UW_MissionBuilder_MissionSelectionMapList_C* ParentWidget;                                 // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void AddNewLevel(const class FString& LevelName, struct FLevelDataLookupTable& LevelData, bool bIsLocked);
	void Construct();
	void ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapSection(int32 EntryPoint);
	void OnLevelSelected(const class FString& SelectedLevel, class UW_MissionBuilder_MissionSelectionMapItem_C* SelectedButton);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_MissionSelectionMapSection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_MissionSelectionMapSection_C")
	}
	static class UW_MissionBuilder_MissionSelectionMapSection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_MissionSelectionMapSection_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_MissionSelectionMapSection_C;

}

