#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_DifficultyItem

#include "Basic.hpp"

#include "W_MissionBuilder_DifficultyItem_classes.hpp"
#include "W_MissionBuilder_DifficultyItem_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_DifficultyItem.W_MissionBuilder_DifficultyItem_C.SetDifficulty
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EMissionBuilderDifficultyPropertyValues Difficulty                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_DifficultyItem_C::SetDifficulty(EMissionBuilderDifficultyPropertyValues Difficulty)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_DifficultyItem_C", "SetDifficulty");

	Params::W_MissionBuilder_DifficultyItem_C_SetDifficulty Parms{};

	Parms.Difficulty = Difficulty;

	UObject::ProcessEvent(Func, &Parms);
}

}

