#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_WatermarkTablet

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_WatermarkTablet.W_MissionBuilder_WatermarkTablet_C
// 0x0018 (0x02E0 - 0x02C8)
class UW_MissionBuilder_WatermarkTablet_C final : public UMissionBuilderWatermarkWidget
{
public:
	class UImage*                                 CMB_Watermark;                                     // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Lines;                                             // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                MissionBuilder_Overlay;                            // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_WatermarkTablet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_WatermarkTablet_C")
	}
	static class UW_MissionBuilder_WatermarkTablet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_WatermarkTablet_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_WatermarkTablet_C;

}

