#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_CheckboxArrayElement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_CheckboxArrayElement.W_MissionBuilder_CheckboxArrayElement_C
// 0x0048 (0x0310 - 0x02C8)
class UW_MissionBuilder_CheckboxArrayElement_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonRichTextBlock*                   txt_Title;                                         // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_MissionBuilder_CheckBox_C*           W_MissionBuilder_CheckBox;                         // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   DefaultText;                                       // 0x02E0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          IsCheckedByDefault;                                // 0x02F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2F9[0x3];                                      // 0x02F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Index_0;                                           // 0x02FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 Index, bool IsChecked)> OnCheckboxElementChanged;            // 0x0300(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Construct();
	void Destruct();
	void ExecuteUbergraph_W_MissionBuilder_CheckboxArrayElement(int32 EntryPoint);
	void OnCheckboxOptionChanged(class FName PropertyName, bool NewBoolValue);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_CheckboxArrayElement_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_CheckboxArrayElement_C")
	}
	static class UW_MissionBuilder_CheckboxArrayElement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_CheckboxArrayElement_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_CheckboxArrayElement_C;

}

