#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_MissionSelectionMapSection

#include "Basic.hpp"

#include "W_MissionBuilder_MissionSelectionMapSection_classes.hpp"
#include "W_MissionBuilder_MissionSelectionMapSection_parameters.hpp"


namespace SDK
{

// Function W_MissionBuilder_MissionSelectionMapSection.W_MissionBuilder_MissionSelectionMapSection_C.AddNewLevel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    LevelName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FLevelDataLookupTable&           LevelData                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bIsLocked                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapSection_C::AddNewLevel(const class FString& LevelName, struct FLevelDataLookupTable& LevelData, bool bIsLocked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapSection_C", "AddNewLevel");

	Params::W_MissionBuilder_MissionSelectionMapSection_C_AddNewLevel Parms{};

	Parms.LevelName = std::move(LevelName);
	Parms.LevelData = std::move(LevelData);
	Parms.bIsLocked = bIsLocked;

	UObject::ProcessEvent(Func, &Parms);

	LevelData = std::move(Parms.LevelData);
}


// Function W_MissionBuilder_MissionSelectionMapSection.W_MissionBuilder_MissionSelectionMapSection_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MissionBuilder_MissionSelectionMapSection_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapSection_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MissionBuilder_MissionSelectionMapSection.W_MissionBuilder_MissionSelectionMapSection_C.ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapSection
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapSection_C::ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapSection(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapSection_C", "ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapSection");

	Params::W_MissionBuilder_MissionSelectionMapSection_C_ExecuteUbergraph_W_MissionBuilder_MissionSelectionMapSection Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MissionBuilder_MissionSelectionMapSection.W_MissionBuilder_MissionSelectionMapSection_C.OnLevelSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    SelectedLevel                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UW_MissionBuilder_MissionSelectionMapItem_C*SelectedButton                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UW_MissionBuilder_MissionSelectionMapSection_C::OnLevelSelected(const class FString& SelectedLevel, class UW_MissionBuilder_MissionSelectionMapItem_C* SelectedButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MissionBuilder_MissionSelectionMapSection_C", "OnLevelSelected");

	Params::W_MissionBuilder_MissionSelectionMapSection_C_OnLevelSelected Parms{};

	Parms.SelectedLevel = std::move(SelectedLevel);
	Parms.SelectedButton = SelectedButton;

	UObject::ProcessEvent(Func, &Parms);
}

}

