#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilder_Watermark

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MissionBuilder_Watermark.W_MissionBuilder_Watermark_C
// 0x0008 (0x02D0 - 0x02C8)
class UW_MissionBuilder_Watermark_C final : public UMissionBuilderWatermarkWidget
{
public:
	class UImage*                                 Image_94;                                          // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MissionBuilder_Watermark_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MissionBuilder_Watermark_C")
	}
	static class UW_MissionBuilder_Watermark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MissionBuilder_Watermark_C>();
	}
};
DUMPER7_ASSERTS_UW_MissionBuilder_Watermark_C;

}

