#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MissionBuilderPageBtn

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilderPageBtn_C_BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature final
{
public:
	bool                                          bNewCheckState;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilderPageBtn_C_BndEvt__W_DifficultyModalEntry_W_OnOffButton_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature;

// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.ExecuteUbergraph_W_MissionBuilderPageBtn
// 0x0008 (0x0008 - 0x0000)
struct W_MissionBuilderPageBtn_C_ExecuteUbergraph_W_MissionBuilderPageBtn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bNewCheckState;         // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilderPageBtn_C_ExecuteUbergraph_W_MissionBuilderPageBtn;

// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilderPageBtn_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilderPageBtn_C_PreConstruct;

// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.SetButtonSelected
// 0x0001 (0x0001 - 0x0000)
struct W_MissionBuilderPageBtn_C_SetButtonSelected final
{
public:
	bool                                          bSelected;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_MissionBuilderPageBtn_C_SetButtonSelected;

// Function W_MissionBuilderPageBtn.W_MissionBuilderPageBtn_C.SetButtonText
// 0x0018 (0x0018 - 0x0000)
struct W_MissionBuilderPageBtn_C_SetButtonText final
{
public:
	class FText                                   CategoryText;                                      // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_W_MissionBuilderPageBtn_C_SetButtonText;

}

