#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Scope_ACOG

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Scope_ACOG.BP_Scope_ACOG_C
// 0x0000 (0x1840 - 0x1840)
class UBP_Scope_ACOG_C final : public UScopedWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Scope_ACOG_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Scope_ACOG_C")
	}
	static class UBP_Scope_ACOG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Scope_ACOG_C>();
	}
};
DUMPER7_ASSERTS_UBP_Scope_ACOG_C;

}

