#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Rifle_RK1Grip

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Rifle_RK1Grip.Rifle_RK1Grip_C
// 0x0000 (0x10D0 - 0x10D0)
class URifle_RK1Grip_C final : public UWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Rifle_RK1Grip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Rifle_RK1Grip_C")
	}
	static class URifle_RK1Grip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URifle_RK1Grip_C>();
	}
};
DUMPER7_ASSERTS_URifle_RK1Grip_C;

}

