#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scope_Reflex

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Scope_Reflex.Scope_Reflex_C
// 0x0000 (0x1840 - 0x1840)
class UScope_Reflex_C final : public UScopedWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Scope_Reflex_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Scope_Reflex_C")
	}
	static class UScope_Reflex_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScope_Reflex_C>();
	}
};
DUMPER7_ASSERTS_UScope_Reflex_C;

}

