#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shotgun_Laser

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Shotgun_Laser.Shotgun_Laser_C
// 0x0000 (0x1110 - 0x1110)
class UShotgun_Laser_C final : public ULaserAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Shotgun_Laser_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Shotgun_Laser_C")
	}
	static class UShotgun_Laser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShotgun_Laser_C>();
	}
};
DUMPER7_ASSERTS_UShotgun_Laser_C;

}

